### ISSUE TITLE
Convert String to Listformat

### ISSUE THREAD

**Issue by Korosensei42** [diproche/swiserver#1]
Currently the Postbody-data does return a single atom, but instead a list would be needed as input for diproche_fo.

**Comment by Korosensei42** [comment]
@TimothyGillespie, @RonjaKaehne, it would be great if one of you had time to attempt solving this problem.

**Comment by Khazuar** [comment]
The only way I can think of this is: If this was a Javascript-program, and we had a string `"{ foo: \"bar"\}"`, we could convert it to the object `{ foo: "bar" }` by calling `JSON.parse` or `eval` on it.

**Comment by TimothyGillespie** [comment]
I would, but I don't really know how to get it running. I tried running it. Pulling diproche8 into the same file and declaring it as a module but this didn't seem to be how you use it.
I also don't understand the issue right now too, which might be because I cannot see the output.

**Comment by Khazuar** [comment]
This seems to be resolved now.
